### PR TITLE
Add survey ID determination for invalid survey, add read methods for survey/tokens

### PR DESCRIPTION
**Pull request by kjona**
Hi, I worked on the tests and made the survey ID determination for an invalid survey dynamic.

### CODE REVIEW

**Comment by kjona** [comment]
I added some read methods for survey (get_summary) and tokens (list_participants, get_participant_properties) which I have added here.

**Comment by lindsay-stevens** [comment]
Thanks very much for this, it looks great. I meant to check it out locally
the first time but haven't gotten to it yet. Hope to soon.

Are you planning on building this out further? So I know whether to update
the PyPI package with this PR or wait a bit.

**Comment by kjona** [comment]
Hi, good to hear from you. Yes, I am playing around with the RC2 API and will have to send invites and read out token responses. Your package helped me a lot to get started and get to know the nitty-gritty of the API (e.g. positinonal arguments). However, I would ideally like to change/extend the interface of the package to improve the usability and apply DRY/KISS principles. I would be happy to discuss these ideas with you. What do you think?

**Comment by kjona** [comment]
I guess it will be hard to merge these changes. I will close this pull request and will apply changes in an updated fork.

**Pull request closed without merging**
